const actionTypes = Object.freeze({
    // PRODUCT CATEGORY
    PRODUCT_CATEGORY_START: 'PRODUCT_CATEGORY_START',
    PRODUCT_CATEGORY_FAIDED: 'PRODUCT_CATEGORY_FAIDED',
    PRODUCT_CATEGORY_SUCCESS: 'PRODUCT_CATEGORY_SUCCESS',
    GET_LIST_PRODUCT_CATEGORY_SUCCESS: 'GET_LIST_PRODUCT_CATEGORY_SUCCESS',
    GET_PRODUCT_CATEGORY_SUCCESS: 'GET_PRODUCT_CATEGORY_SUCCESS',
    CREATE_PRODUCT_CATEGORY_SUCCESS: 'CREATE_PRODUCT_CATEGORY_SUCCESS',
    DELETE_LIST_PRODUCT_CATEGORY_SUCCESS: 'DELETE_LIST_PRODUCT_CATEGORY_SUCCESS',
    EDIT_PRODUCT_CATEGORY_SUCCESS: 'EDIT_PRODUCT_CATEGORY_SUCCESS',
    EDIT_LIST_PRODUCT_CATEGORY_SUCCESS: 'EDIT_LIST_PRODUCT_CATEGORY_SUCCESS',
    ON_CHANGE_PRODUCT_CATEGORY: 'ON_CHANGE_PRODUCT_CATEGORY',
    SET_DATA_PRODUCT_CATEGORY: 'SET_DATA_PRODUCT_CATEGORY',

    // SHOP
    SHOP_START: 'SHOP_START',
    SHOP_FAIDED: 'SHOP_FAIDED',
    SHOP_SUCCESS: 'SHOP_SUCCESS',

    GET_LIST_SHOP_SUCCESS: 'GET_LIST_SHOP_SUCCESS',
    GET_SHOP_SUCCESS: 'GET_SHOP_SUCCESS',
    CREATE_SHOP_SUCCESS: 'CREATE_SHOP_SUCCESS',
    DELETE_LIST_SHOP_SUCCESS: 'DELETE_LIST_SHOP_SUCCESS',
    EDIT_SHOP_SUCCESS: 'EDIT_SHOP_SUCCESS',
    EDIT_LIST_SHOP_SUCCESS: 'EDIT_LIST_SHOP_SUCCESS',
    ON_CHANGE_SHOP: 'ON_CHANGE_SHOP',
    SET_DATA_SHOP: 'SET_DATA_SHOP',

    // STAFF
    STAFF_START: 'STAFF_START',
    STAFF_FAIDED: 'STAFF_FAIDED',
    STAFF_SUCCESS: 'STAFF_SUCCESS',

    GET_LIST_STAFF_SUCCESS: 'GET_LIST_STAFF_SUCCESS',
    GET_STAFF_SUCCESS: 'GET_STAFF_SUCCESS',
    CREATE_STAFF_SUCCESS: 'CREATE_STAFF_SUCCESS',
    DELETE_LIST_STAFF_SUCCESS: 'DELETE_LIST_STAFF_SUCCESS',
    EDIT_STAFF_SUCCESS: 'EDIT_STAFF_SUCCESS',
    EDIT_LIST_STAFF_SUCCESS: 'EDIT_LIST_STAFF_SUCCESS',
    ON_CHANGE_STAFF: 'ON_CHANGE_STAFF',
    SET_DATA_STAFF: 'SET_DATA_STAFF',

    // ORDER
    ORDER_START: 'ORDER_START',
    ORDER_FAIDED: 'ORDER_FAIDED',
    ORDER_SUCCESS: 'ORDER_SUCCESS',

    GET_LIST_ORDER_SUCCESS: 'GET_LIST_ORDER_SUCCESS',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    DELETE_LIST_ORDER_SUCCESS: 'DELETE_LIST_ORDER_SUCCESS',
    EDIT_ORDER_SUCCESS: 'EDIT_ORDER_SUCCESS',
    EDIT_LIST_ORDER_SUCCESS: 'EDIT_LIST_ORDER_SUCCESS',
    ON_CHANGE_ORDER: 'ON_CHANGE_ORDER',
    SET_DATA_ORDER: 'SET_DATA_ORDER',

    // CUSTOMER
    CUSTOMER_START: 'CUSTOMER_START',
    CUSTOMER_FAIDED: 'CUSTOMER_FAIDED',
    CUSTOMER_SUCCESS: 'CUSTOMER_SUCCESS',

    GET_LIST_CUSTOMER_SUCCESS: 'GET_LIST_CUSTOMER_SUCCESS',
    GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
    DELETE_LIST_CUSTOMER_SUCCESS: 'DELETE_LIST_CUSTOMER_SUCCESS',
    EDIT_CUSTOMER_SUCCESS: 'EDIT_CUSTOMER_SUCCESS',
    EDIT_LIST_CUSTOMER_SUCCESS: 'EDIT_LIST_CUSTOMER_SUCCESS',
    ON_CHANGE_CUSTOMER: 'ON_CHANGE_CUSTOMER',
    SET_DATA_CUSTOMER: 'SET_DATA_CUSTOMER',
})

export default actionTypes;