const action_types = Object.freeze({

    // PRODUCT
    PRODUCT_START: 'PRODUCT_START',
    PRODUCT_FAIDED: 'PRODUCT_FAIDED',
    PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',

    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    ON_CHANGE_PRODUCT: 'ON_CHANGE_PRODUCT',
    CLICK_EDIT_PRODUCT: 'CLICK_EDIT_PRODUCT',

    // VARIANT
    VARIANT_START: 'VARIANT_START',
    VARIANT_FAIDED: 'VARIANT_FAIDED',
    VARIANT_SUCCESS: 'VARIANT_SUCCESS',

    GET_VARIANT_SUCCESS: 'GET_VARIANT_SUCCESS',
    ON_CHANGE_VARIANT: 'ON_CHANGE_VARIANT',
    CLICK_EDIT_VARIANT: 'CLICK_EDIT_VARIANT',

    // BRAND
    BRAND_START: 'BRAND_START',
    BRAND_FAIDED: 'BRAND_FAIDED',
    BRAND_SUCCESS: 'BRAND_SUCCESS',

    GET_LIST_BRAND_SUCCESS: 'GET_LIST_BRAND_SUCCESS',
    ON_CHANGE_BRAND: 'ON_CHANGE_BRAND',

    // TAG
    TAG_START: 'TAG_START',
    TAG_FAIDED: 'TAG_FAIDED',
    TAG_SUCCESS: 'TAG_SUCCESS',

    GET_LIST_TAG_SUCCESS: 'GET_LIST_TAG_SUCCESS',
    ON_CHANGE_TAG: 'ON_CHANGE_TAG',

    // CATEGORY
    CATEGORY_START: 'CATEGORY_START',
    CATEGORY_FAIDED: 'CATEGORY_FAIDED',
    CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',

    GET_LIST_CATEGORY_SUCCESS: 'GET_LIST_CATEGORY_SUCCESS',
    ON_CHANGE_CATEGORY: 'ON_CHANGE_CATEGORY',

    // VARIANT_ATTRIBUTE_GROUP
    VARIANT_ATTRIBUTE_GROUP_START: 'VARIANT_ATTRIBUTE_GROUP_START',
    VARIANT_ATTRIBUTE_GROUP_FAIDED: 'VARIANT_ATTRIBUTE_GROUP_FAIDED',
    VARIANT_ATTRIBUTE_GROUP_SUCCESS: 'VARIANT_ATTRIBUTE_GROUP_SUCCESS',

    GET_LIST_VARIANT_ATTRIBUTE_GROUP_SUCCESS: 'GET_LIST_VARIANT_ATTRIBUTE_GROUP_SUCCESS',
    ON_CHANGE_CATEGORY: 'ON_CHANGE_CATEGORY',
})

export default action_types;