const actionTypes = Object.freeze({
    // STATISTICAL
    STATISTICAL_START: 'STATISTICAL_START',
    STATISTICAL_FAIDED: 'STATISTICAL_FAIDED',
    STATISTICAL_SUCCESS: 'STATISTICAL_SUCCESS',
    GET_VIEW_WEB_SUCCESS: 'GET_VIEW_WEB_SUCCESS',
    GET_VIEW_PRODUCT_SUCCESS: 'GET_VIEW_PRODUCT_SUCCESS',
    ON_CHANGE_STATISTICAL: 'ON_CHANGE_STATISTICAL',
    SET_STATISTICAL: 'SET_STATISTICAL',
})

export default actionTypes;